{{- if .Values.ingress.enabled -}}
{{- $fullName := include "minio.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ $fullName }}
spec:
  domains:
    {{- range .Values.ingress.hosts }}
    - {{ . | quote }}
    {{- end }}
{{- end }}