{{- $fullName := include "minio.fullname" . -}}
{{- if and .Values.metrics.serviceMonitor.enabled .Values.metrics.serviceMonitor.security.enabled }}
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSecurityPolicy
metadata:
  name: {{ $fullName }}-prometheus
  labels:
    app: {{ template "minio.name" . }}
    chart: {{ template "minio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  description: A policy designed to completely lock down network access to prometheus metrics
  rule:
  - action: allow
    priority: 2147483647
    match:
      expr:
        expression: "request.path.matches('/minio/prometheus/') == false"
    description: Rule matching all IPs with priority 2147483647, set to deny.
  - action: deny
    priority: 1001
    match:
      expr:
        expression: "request.path.matches('/minio/prometheus/')"
    description: Deny access to prometheus if IP check fails
  - action: allow
    priority: 1000
    match:
      versionedExpr: SRC_IPS_V1
      config:
        srcIpRanges:
      {{- range .Values.metrics.serviceMonitor.security.whitelist }}
        - {{ . | quote }}
      {{- end }}
    description: Whitelisted IP addresses that can reach the prometheus endpoint via the public loadbalancer
{{- end }}